/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proyecto.git;

public class App {
    public String getGreeting() {
        String hola="hola";
        return hola + "Cesar";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
